# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 22:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpostorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impostor_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name=b"Impostor's IP address")),
                ('logged_in', models.DateTimeField(auto_now_add=True, verbose_name=b'Logged on')),
                ('logged_out', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(blank=True, db_index=True, max_length=32)),
                ('imposted_as', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imposted_as', to=settings.AUTH_USER_MODEL,
 verbose_name=b'Logged in as')),
                ('impostor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impostor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
